import { useState } from 'react';
import { supabase } from '../../lib/supabase';
import { useStore } from '@nanostores/react';
import { adminLang, adminTranslations } from '../../stores/i18nStore';

interface CategoryFormProps {
    modalId?: string;
    onCreated?: () => void;
}

export default function CategoryForm({ modalId = 'new_category_modal', onCreated }: CategoryFormProps) {
    const lang = useStore(adminLang);
    const t = adminTranslations[lang];

    const [loading, setLoading] = useState(false);
    const [nameEs, setNameEs] = useState('');
    const [nameZh, setNameZh] = useState('');
    const [slug, setSlug] = useState('');

    // Auto-generate slug from nameEs
    const handleNameEsChange = (value: string) => {
        setNameEs(value);
        const generatedSlug = value
            .toLowerCase()
            .normalize('NFD')
            .replace(/[\u0300-\u036f]/g, '')
            .replace(/[^a-z0-9\s-]/g, '')
            .replace(/\s+/g, '-')
            .replace(/-+/g, '-')
            .replace(/^-|-$/g, '');
        setSlug(generatedSlug);
    };

    const closeModal = () => {
        const modal = document.getElementById(modalId) as HTMLDialogElement;
        if (modal) modal.close();
    };

    const resetForm = () => {
        setNameEs('');
        setNameZh('');
        setSlug('');
    };

    const handleCancel = () => {
        resetForm();
        closeModal();
    };

    const handleSubmit = async (e: React.FormEvent) => {
        e.preventDefault();
        setLoading(true);

        // Get the highest display_order
        const { data: categories } = await supabase
            .from('categories')
            .select('display_order')
            .order('display_order', { ascending: false })
            .limit(1);

        const nextOrder = categories && categories.length > 0 ? categories[0].display_order + 1 : 1;

        const { error } = await supabase
            .from('categories')
            .insert([{
                name_es: nameEs,
                name_zh: nameZh,
                slug: slug,
                display_order: nextOrder
            }]);

        setLoading(false);

        if (error) {
            if (error.code === '23505') {
                alert(t.slugExists);
            } else {
                alert('Error: ' + error.message);
            }
        } else {
            resetForm();
            closeModal();
            // Recargar para actualizar la lista
            if (onCreated) {
                onCreated();
            } else {
                window.location.reload();
            }
        }
    };

    return (
        <>
            <h3 className="font-['Playfair_Display'] font-bold text-xl text-[#1C1C1E] mb-1">{t.createCategory}</h3>
            <p className="text-[#5A5A5C] text-sm mb-5">{t.organizeMenu}</p>
            
            <form onSubmit={handleSubmit} className="space-y-4">
                <div className="space-y-1.5">
                    <label className="text-sm font-medium text-[#5A5A5C]">{t.categoryNameEs}</label>
                    <input
                        type="text"
                        placeholder="Ej: Sopas"
                        className="w-full px-4 py-2.5 bg-[#F7F7F2] border border-[#E8C4C4]/30 rounded-xl text-[#1C1C1E] placeholder-[#5A5A5C]/40 focus:outline-none focus:ring-2 focus:ring-[#B84A4A]/30 focus:border-[#B84A4A]/50 transition-all"
                        required
                        value={nameEs}
                        onChange={(e) => handleNameEsChange(e.target.value)}
                    />
                </div>

                <div className="space-y-1.5">
                    <label className="text-sm font-medium text-[#5A5A5C]">{t.categoryNameZh}</label>
                    <input
                        type="text"
                        placeholder="Ej: 汤"
                        className="w-full px-4 py-2.5 bg-[#F7F7F2] border border-[#E8C4C4]/30 rounded-xl text-[#1C1C1E] placeholder-[#5A5A5C]/40 focus:outline-none focus:ring-2 focus:ring-[#B84A4A]/30 focus:border-[#B84A4A]/50 transition-all font-['Noto_Serif_SC']"
                        required
                        value={nameZh}
                        onChange={(e) => setNameZh(e.target.value)}
                    />
                </div>

                <div className="space-y-1.5">
                    <div className="flex items-center justify-between">
                        <label className="text-sm font-medium text-[#5A5A5C]">{t.categorySlug}</label>
                        <span className="text-xs text-[#5A5A5C]/50">{t.autoGenerated}</span>
                    </div>
                    <input
                        type="text"
                        placeholder="sopas"
                        className="w-full px-4 py-2.5 bg-[#F7F7F2] border border-[#E8C4C4]/30 rounded-xl text-[#1C1C1E] placeholder-[#5A5A5C]/40 focus:outline-none focus:ring-2 focus:ring-[#B84A4A]/30 focus:border-[#B84A4A]/50 transition-all font-mono text-sm"
                        required
                        value={slug}
                        onChange={(e) => setSlug(e.target.value)}
                    />
                </div>

                <div className="flex gap-3 pt-4">
                    <button
                        type="submit"
                        className="flex-1 py-2.5 px-4 bg-[#B84A4A] hover:bg-[#8B3A3A] text-white font-semibold rounded-xl shadow-md shadow-[#B84A4A]/20 transition-all disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center gap-2"
                        disabled={loading}
                    >
                        {loading && <span className="loading loading-spinner loading-sm"></span>}
                        {t.save}
                    </button>
                    <button
                        type="button"
                        className="flex-1 py-2.5 px-4 bg-[#F7F7F2] text-[#5A5A5C] font-medium rounded-xl hover:bg-[#E8C4C4]/30 transition-colors"
                        onClick={handleCancel}
                        disabled={loading}
                    >
                        {t.cancel}
                    </button>
                </div>
            </form>
        </>
    );
}
