import { atom } from 'nanostores';

export type AdminLanguage = 'es' | 'zh';

const STORAGE_KEY = 'admin-lang';

// Función para obtener el idioma inicial desde localStorage
function getInitialLang(): AdminLanguage {
    if (typeof window !== 'undefined') {
        const stored = localStorage.getItem(STORAGE_KEY);
        if (stored === 'es' || stored === 'zh') {
            return stored;
        }
    }
    return 'es'; // Default
}

// Inicializar con el valor guardado o default
export const adminLang = atom<AdminLanguage>(getInitialLang());

export function toggleAdminLang() {
    const current = adminLang.get();
    const newLang = current === 'es' ? 'zh' : 'es';
    adminLang.set(newLang);
    
    // Persistir en localStorage
    if (typeof window !== 'undefined') {
        localStorage.setItem(STORAGE_KEY, newLang);
    }
}

export const adminTranslations = {
    es: {
        // Navigation
        dashboard: 'Panel de Control',
        categories: 'Categorías',
        logout: 'Cerrar Sesión',
        backToPanel: 'Volver al panel',
        support: 'Contactar soporte',
        
        // Dashboard
        manageMenu: 'Gestiona tu menú y productos',
        createProduct: 'Crear Producto',
        generateQR: 'Generar QR',
        
        // Products
        products: 'Productos',
        loadingProducts: 'Cargando productos...',
        noProducts: 'No hay productos',
        noProductsDesc: 'Comienza agregando tu primer producto al menú',
        searchProducts: 'Buscar productos...',
        allCategories: 'Todas las categorías',
        allStatus: 'Todos',
        availableOnly: 'Disponibles',
        unavailableOnly: 'Agotados',
        sortBy: 'Ordenar por',
        sortNameAsc: 'Nombre A-Z',
        sortNameDesc: 'Nombre Z-A',
        sortPriceAsc: 'Precio menor',
        sortPriceDesc: 'Precio mayor',
        noResults: 'No se encontraron productos',
        clearFilters: 'Limpiar filtros',
        resultsCount: 'productos',
        
        // Product Form
        addNewProduct: 'Agrega un nuevo producto al menú',
        productNames: 'Nombres del producto',
        spanish: 'Español',
        chinese: '中文',
        description: 'Descripción',
        optional: 'Opcional',
        price: 'Precio',
        minOne: 'Mínimo 1',
        image: 'Imagen',
        clickToUpload: 'Haz clic para subir una imagen',
        saving: 'Guardando...',
        selectAtLeastOne: 'Debes seleccionar al menos una categoría',
        productCreated: '¡Producto creado exitosamente!',
        productUpdated: '¡Producto actualizado exitosamente!',
        editProduct: 'Editar Producto',
        updateProduct: 'Actualizar',
        editProductDesc: 'Modifica los detalles del producto',
        keepCurrentImage: 'Mantener imagen actual',
        changeImage: 'Cambiar imagen',
        
        // Categories
        manageCategories: 'Gestionar Categorías',
        organizeMenu: 'Organiza los productos del menú',
        createCategory: 'Crear Categoría',
        editCategory: 'Editar Categoría',
        loadingCategories: 'Cargando categorías...',
        noCategories: 'No hay categorías',
        noCategoriesDesc: 'Crea tu primera categoría para organizar el menú',
        noCategoriesLink: 'No hay categorías creadas.',
        createCategoriesLink: 'Crear categorías',
        categoryNameEs: 'Nombre (ES)',
        categoryNameZh: 'Nombre (ZH)',
        categorySlug: 'Slug',
        autoGenerated: 'Auto-generado',
        slugExists: 'El slug ya existe. Por favor usa otro nombre o slug.',
        
        // QR Generator
        qrGenerator: 'Generador de QR',
        downloadQRs: 'Descarga códigos QR para tu menú',
        qrDuration: '¿Cuánto dura este QR?',
        qrInfo: 'Este QR es ETERNO mientras tu dominio web exista. Si actualizas platos o precios, el QR sigue funcionando.',
        downloadPDF: 'Descargar PDF (x6 QRs)',
        pdfIncludes: 'El PDF incluye 6 códigos QR listos para imprimir',
        
        // Common
        save: 'Guardar',
        edit: 'Editar',
        delete: 'Eliminar',
        cancel: 'Cancelar',
        loading: 'Cargando...',
        stock: 'Stock',
        available: 'Disponible',
        outOfStock: 'Agotado',
        noCategory: 'Sin categoría',
        selectCategories: 'Seleccionar Categorías',
        name: 'Nombre',
        order: 'Orden',
        moveUp: 'Subir',
        moveDown: 'Bajar',
        
        // Confirmations
        confirmDelete: '¿Estás seguro de que deseas eliminar',
        confirmDeleteCategory: '¿Eliminar la categoría',
        categoryHasProducts: 'tiene productos asociados. ¿Estás seguro de eliminarla?',
        actionCantUndo: 'Esta acción no se puede deshacer.',
    },
    zh: {
        // Navigation
        dashboard: '控制面板',
        categories: '类别',
        logout: '退出登录',
        backToPanel: '返回面板',
        support: '联系支持',
        
        // Dashboard
        manageMenu: '管理您的菜单和产品',
        createProduct: '新增产品',
        generateQR: '生成二维码',
        
        // Products
        products: '产品管理',
        loadingProducts: '正在加载产品...',
        noProducts: '暂无产品',
        noProductsDesc: '开始添加您的第一个产品到菜单',
        searchProducts: '搜索产品...',
        allCategories: '所有类别',
        allStatus: '全部',
        availableOnly: '有货',
        unavailableOnly: '缺货',
        sortBy: '排序',
        sortNameAsc: '名称 A-Z',
        sortNameDesc: '名称 Z-A',
        sortPriceAsc: '价格从低到高',
        sortPriceDesc: '价格从高到低',
        noResults: '未找到产品',
        clearFilters: '清除筛选',
        resultsCount: '个产品',
        
        // Product Form
        addNewProduct: '向菜单添加新产品',
        productNames: '产品名称',
        spanish: 'Español',
        chinese: '中文',
        description: '描述',
        optional: '可选',
        price: '价格',
        minOne: '至少1个',
        image: '图片',
        clickToUpload: '点击上传图片',
        saving: '保存中...',
        selectAtLeastOne: '请至少选择一个类别',
        productCreated: '产品创建成功！',
        productUpdated: '产品更新成功！',
        editProduct: '编辑产品',
        updateProduct: '更新',
        editProductDesc: '修改产品详情',
        keepCurrentImage: '保留当前图片',
        changeImage: '更换图片',
        
        // Categories
        manageCategories: '管理类别',
        organizeMenu: '整理菜单产品',
        createCategory: '创建类别',
        editCategory: '编辑类别',
        loadingCategories: '正在加载类别...',
        noCategories: '暂无类别',
        noCategoriesDesc: '创建您的第一个类别来整理菜单',
        noCategoriesLink: '暂无类别',
        createCategoriesLink: '创建类别',
        categoryNameEs: '名称 (ES)',
        categoryNameZh: '名称 (ZH)',
        categorySlug: 'Slug',
        autoGenerated: '自动生成',
        slugExists: 'Slug已存在，请使用其他名称或slug。',
        
        // QR Generator
        qrGenerator: '二维码生成器',
        downloadQRs: '下载菜单二维码',
        qrDuration: '二维码有效期？',
        qrInfo: '只要您的网站域名存在，此二维码永久有效。',
        downloadPDF: '下载 PDF (x6)',
        pdfIncludes: 'PDF包含6个可打印的二维码',
        
        // Common
        save: '保存',
        edit: '编辑',
        delete: '删除',
        cancel: '取消',
        loading: '加载中...',
        stock: '库存',
        available: '有货',
        outOfStock: '缺货',
        noCategory: '无类别',
        selectCategories: '选择类别',
        name: '名称',
        order: '顺序',
        moveUp: '上移',
        moveDown: '下移',
        
        // Confirmations
        confirmDelete: '确定要删除',
        confirmDeleteCategory: '删除类别',
        categoryHasProducts: '有关联产品。确定要删除吗？',
        actionCantUndo: '此操作无法撤销。',
    }
};
